networks:
  default:
    driver: bridge
    name: roboshop
    #external: true #I created network already using docker network create roboshop
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:  #docker volume create rabbitmq
services:
  mongodb:
    image: nanda777/mongodb
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: nanda777/catalogue
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: nanda777/redis
    container_name: redis
    volumes:
    - redis:/data
  user:
    image: nanda777/user
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: nanda777/cart
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: nanda777/mysql
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: nanda777/shipping
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    image: nanda777/rabbitmq
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: nanda777/payment
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    image: nanda777/frontend
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment
